export const ALPHA_NUMERIC_INPUT_ERROR = "Enter a valid Roman Numeral or Integer";
export const INPUT_RANGE_ERROR = "Integers should range between 1 to 3999";
export const INVALID_INPUT_ERROR = "Invalid input";

export const ROMAN_LETTERS_ARRAY = [
    "",
    "C",
    "CC",
    "CCC",
    "CD",
    "D",
    "DC",
    "DCC",
    "DCCC",
    "CM",
    "",
    "X",
    "XX",
    "XXX",
    "XL",
    "L",
    "LX",
    "LXX",
    "LXXX",
    "XC",
    "",
    "I",
    "II",
    "III",
    "IV",
    "V",
    "VI",
    "VII",
    "VIII",
    "IX",
  ];

  export const ROMAN_NUMERALS_KEY_OBJ = {
    M: 1000,
    CM: 900,
    D: 500,
    CD: 400,
    C: 100,
    XC: 90,
    L: 50,
    XL: 40,
    X: 10,
    IX: 9,
    V: 5,
    IV: 4,
    I: 1,
  };
